spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task-service
    username: root
    password: "@tanaLoLo33"
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: USER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 5001


